import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.58.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const GROK_API_KEY = Deno.env.get('GROK_API_KEY');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');

    if (!GROK_API_KEY) {
      throw new Error('GROK_API_KEY is not set');
    }

    if (!SUPABASE_SERVICE_ROLE_KEY || !SUPABASE_URL) {
      throw new Error('Supabase configuration is missing');
    }

    const { accountId } = await req.json();

    if (!accountId) {
      throw new Error('Account ID is required');
    }

    // Initialize Supabase client
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Get account details
    const { data: account, error: accountError } = await supabase
      .from('comptes')
      .select('nom, prompt')
      .eq('id', accountId)
      .single();

    if (accountError || !account) {
      console.error('Error fetching account:', accountError);
      throw new Error('Account not found');
    }

    console.log('Generating script for account:', account);

    // Create prompt for Grok
    const grokPrompt = `Génère un nouveau script de vidéo tiktok viral pour un personnage généré par IA dont les infos sont ${account.nom} - ${account.prompt || 'Personnage générique'}`;

    // Call Grok API (xAI uses OpenAI-compatible API)
    const response = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GROK_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'grok-beta',
        messages: [
          {
            role: 'system',
            content: 'Tu es un expert en création de contenu viral pour TikTok. Génère des scripts courts, engageants et divertissants.'
          },
          {
            role: 'user',
            content: grokPrompt
          }
        ],
        max_tokens: 500,
        temperature: 0.8,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Grok API error:', errorData);
      throw new Error(`Grok API error: ${response.status}`);
    }

    const grokData = await response.json();
    const generatedScript = grokData.choices[0]?.message?.content;

    if (!generatedScript) {
      throw new Error('No script generated by Grok');
    }

    console.log('Generated script:', generatedScript);

    // Save the generated script to database
    const { data: savedScript, error: saveError } = await supabase
      .from('scripts')
      .insert({
        compte_id: accountId,
        script_text: generatedScript,
        statut: 'en_attente'
      })
      .select()
      .single();

    if (saveError) {
      console.error('Error saving script:', saveError);
      throw new Error('Failed to save script');
    }

    console.log('Script saved successfully:', savedScript);

    return new Response(JSON.stringify({ 
      success: true, 
      script: savedScript,
      generated_text: generatedScript 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in generate-script function:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'An error occurred' 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});