// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avtqebzzgjlmvplulgnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dHFlYnp6Z2psbXZwbHVsZ25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODAwODksImV4cCI6MjA3NDU1NjA4OX0.F7PfQxtVQkofEwIJ-BNfjFJF2ymLOfrMFsgflClrufI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});